In [1]:
import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
import matplotlib.cm as cm
import itertools
from IPython.display import display, HTML
import plotly.graph_objs as go
from plotly.offline import init_notebook_mode,iplot
init_notebook_mode(connected=True)
warnings.filterwarnings("ignore")
plt.rcParams["patch.force_edgecolor"] = True
plt.style.use('fivethirtyeight')
mpl.rc('patch', edgecolor = 'dimgray', linewidth=1)
%matplotlib inline

In [2]:
df = pd.read_csv('countries of the world.csv')
df.head()

,Country,Region,Population,Area (sq. mi.),Pop. Density (per sq. mi.),Coastline (coast/area ratio),Net migration,Infant mortality (per 1000 births),GDP ($ per capita),Literacy (%),Phones (per 1000),Arable (%),Crops (%),Other (%),Climate,Birthrate,Deathrate,Agriculture,Industry,Service
0,Afghanistan,ASIA (EX. NEAR EAST),31056997,647500,"48,0","0,00","23,06","163,07",700.0,"36,0","3,2","12,13","0,22","87,65",1,"46,6","20,34","0,38","0,24","0,38"
1,Albania,EASTERN EUROPE,3581655,28748,"124,6","1,26","-4,93","21,52",4500.0,"86,5","71,2","21,09","4,42","74,49",3,"15,11","5,22","0,232","0,188","0,579"
2,Algeria,NORTHERN AFRICA,32930091,2381740,"13,8","0,04","-0,39",31,6000.0,"70,0","78,1","3,22","0,25","96,53",1,"17,14","4,61","0,101","0,6","0,298"
3,American Samoa,OCEANIA,57794,199,"290,4","58,29","-20,71","9,27",8000.0,"97,0","259,5",10,15,75,2,"22,46","3,27",NaN,NaN,NaN
4,Andorra,WESTERN EUROPE,71201,468,"152,1","0,00","6,6","4,05",19000.0,"100,0","497,2","2,22",0,"97,78",3,"8,71","6,25",NaN,NaN,NaN

In [3]:
print(df.keys())

Index(['Country', 'Region', 'Population', 'Area (sq. mi.)',
       'Pop. Density (per sq. mi.)', 'Coastline (coast/area ratio)',
       'Net migration', 'Infant mortality (per 1000 births)',
       'GDP ($ per capita)', 'Literacy (%)', 'Phones (per 1000)', 'Arable (%)',
       'Crops (%)', 'Other (%)', 'Climate', 'Birthrate', 'Deathrate',
       'Agriculture', 'Industry', 'Service'],
      dtype='object')

In [4]:
 df = df.rename(columns={
     "Country":"country",
     "Region":"region",
     "Population":"population",
     "Area (sq. mi.)":"area",
     "Pop. Density (per sq. mi.)":"pop_density",
     "Coastline (coast/area ratio)":"coastline",
     "Net migration":"net_migration",
     "Infant mortality (per 1000 births)":"infant_mortality",
     "GDP ($ per capita)": "gdp_capita",
     "Literacy (%)":"literacy",
     "Phones (per 1000)":"phones_per_1000",
     "Arable (%)":"arable",
     "Crops (%)":"crops",
     "Other (%)":"other",
     "Climate":"climate",
     "Birthrate":"birth_rate",
     "Deathrate":"death_rate",
     "Agriculture":"agriculture",
     "Industry":"industry",
     "Service":"service"
     
 })
df.head()

,country,region,population,area,pop_density,coastline,net_migration,infant_mortality,gdp_capita,literacy,phones_per_1000,arable,crops,other,climate,birth_rate,death_rate,agriculture,industry,service
0,Afghanistan,ASIA (EX. NEAR EAST),31056997,647500,"48,0","0,00","23,06","163,07",700.0,"36,0","3,2","12,13","0,22","87,65",1,"46,6","20,34","0,38","0,24","0,38"
1,Albania,EASTERN EUROPE,3581655,28748,"124,6","1,26","-4,93","21,52",4500.0,"86,5","71,2","21,09","4,42","74,49",3,"15,11","5,22","0,232","0,188","0,579"
2,Algeria,NORTHERN AFRICA,32930091,2381740,"13,8","0,04","-0,39",31,6000.0,"70,0","78,1","3,22","0,25","96,53",1,"17,14","4,61","0,101","0,6","0,298"
3,American Samoa,OCEANIA,57794,199,"290,4","58,29","-20,71","9,27",8000.0,"97,0","259,5",10,15,75,2,"22,46","3,27",NaN,NaN,NaN
4,Andorra,WESTERN EUROPE,71201,468,"152,1","0,00","6,6","4,05",19000.0,"100,0","497,2","2,22",0,"97,78",3,"8,71","6,25",NaN,NaN,NaN

In [5]:
df.dtypes

country              object
region               object
population            int64
area                  int64
pop_density          object
coastline            object
net_migration        object
infant_mortality     object
gdp_capita          float64
literacy             object
phones_per_1000      object
arable               object
crops                object
other                object
climate              object
birth_rate           object
death_rate           object
agriculture          object
industry             object
service              object
dtype: object

In [6]:
df.fillna(0,inplace=True)

for column in df.columns:
    try:
        df[column] = df[column].str.replace(',','.').astype(float)
    except:
        print('')

In [7]:
df.dtypes

country              object
region               object
population            int64
area                  int64
pop_density         float64
coastline           float64
net_migration       float64
infant_mortality    float64
gdp_capita          float64
literacy            float64
phones_per_1000     float64
arable              float64
crops               float64
other               float64
climate             float64
birth_rate          float64
death_rate          float64
agriculture         float64
industry            float64
service             float64
dtype: object

In [8]:
df.region.value_counts()

SUB-SAHARAN AFRICA                     51
LATIN AMER. & CARIB                    45
ASIA (EX. NEAR EAST)                   28
WESTERN EUROPE                         28
OCEANIA                                21
NEAR EAST                              16
C.W. OF IND. STATES                    12
EASTERN EUROPE                         12
NORTHERN AFRICA                         6
NORTHERN AMERICA                        5
BALTICS                                 3
Name: region, dtype: int64

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 227 entries, 0 to 226
Data columns (total 20 columns):
country             227 non-null object
region              227 non-null object
population          227 non-null int64
area                227 non-null int64
pop_density         227 non-null float64
coastline           227 non-null float64
net_migration       224 non-null float64
infant_mortality    224 non-null float64
gdp_capita          227 non-null float64
literacy            209 non-null float64
phones_per_1000     223 non-null float64
arable              225 non-null float64
crops               225 non-null float64
other               225 non-null float64
climate             205 non-null float64
birth_rate          224 non-null float64
death_rate          223 non-null float64
agriculture         212 non-null float64
industry            211 non-null float64
service             212 non-null float64
dtypes: float64(16), int64(2), object(2)
memory usage: 35.5+ KB

In [10]:
df.describe()

,population,area,pop_density,coastline,net_migration,infant_mortality,gdp_capita,literacy,phones_per_1000,arable,crops,other,climate,birth_rate,death_rate,agriculture,industry,service
count,2.270000e+02,2.270000e+02,227.000000,227.000000,224.000000,224.000000,227.000000,209.000000,223.000000,225.000000,225.000000,225.000000,205.000000,224.000000,223.000000,212.000000,211.000000,212.000000
mean,2.874028e+07,5.982270e+05,379.047137,21.165330,0.038125,35.506964,9647.136564,82.838278,236.061435,13.797111,4.564222,81.638311,2.139024,22.114732,9.241345,0.150844,0.282711,0.565283
std,1.178913e+08,1.790282e+06,1660.185825,72.286863,4.889269,35.389899,10047.485847,19.722173,227.991829,13.040402,8.361470,16.140835,0.699397,11.176716,4.990026,0.146798,0.138272,0.165841
min,7.026000e+03,2.000000e+00,0.000000,0.000000,-20.990000,2.290000,0.000000,17.600000,0.200000,0.000000,0.000000,33.330000,1.000000,7.290000,2.290000,0.000000,0.020000,0.062000
25%,4.376240e+05,4.647500e+03,29.150000,0.100000,-0.927500,8.150000,1900.000000,70.600000,37.800000,3.220000,0.190000,71.650000,2.000000,12.672500,5.910000,0.037750,0.193000,0.429250
50%,4.786994e+06,8.660000e+04,78.800000,0.730000,0.000000,21.000000,5500.000000,92.500000,176.200000,10.420000,1.030000,85.700000,2.000000,18.790000,7.840000,0.099000,0.272000,0.571000
75%,1.749777e+07,4.418110e+05,190.150000,10.345000,0.997500,55.705000,15700.000000,98.000000,389.650000,20.000000,4.440000,95.440000,3.000000,29.820000,10.605000,0.221000,0.341000,0.678500
max,1.313974e+09,1.707520e+07,16271.500000,870.660000,23.060000,191.190000,55100.000000,100.000000,1035.600000,62.110000,50.680000,100.000000,4.000000,50.730000,29.740000,0.769000,0.906000,0.954000

In [11]:
print(df.sort_values("population",ascending=False)['country'].head(10))
print("----------------------------------")
print(df.sort_values("population",ascending=True)['country'].head(10))

42             China
94             India
214    United States
95         Indonesia
27            Brazil
156         Pakistan
16        Bangladesh
169           Russia
152          Nigeria
103            Japan
Name: country, dtype: object
----------------------------------
174    St Pierre & Miquelon
171            Saint Helena
140              Montserrat
209                  Tuvalu
144                   Nauru
6                  Anguilla
221       Wallis and Futuna
157                   Palau
208       Turks & Caicos Is
47             Cook Islands
Name: country, dtype: object

In [14]:
#Population per country
data = dict(
        type='choropleth',
        locations = df['country'],
        locationmode = 'country names', z = df['population'],
        text = df['country'], colorbar = {'title':'population'},
        colorscale = 'Viridis', reversescale = True)

layout = dict(title='Population per country',
geo = dict(showframe=False,projection={'type':'mercator'}))

choromap = go.Figure(data = [data],layout = layout)
iplot(choromap,validate=False)